#!/bin/sh

#set -x 
#######################################
echo $ZIG_XTENSA
current_dir=$(pwd)
component_dir=$IDF_PATH/components/

echo "$current_dir"
echo "$component_dir"
######################################
echo $IDF_PATH 
source $IDF_PATH/export.sh
source $IDF_PATH/add_path.sh

######################################
cd "$current_dir"/main
$ZIG_XTENSA build "$@"

idf.py set-target esp32s3
idf.py build

ln -s build/compile_commands.json .
