const mmio = @import("mmio");
const types = @import("../../types.zig");

/// ECDSA (Elliptic Curve Digital Signature Algorithm) Accelerator
pub const ECDSA = extern struct {
    /// offset: 0x00
    reserved0: [4]u8,
    /// ECDSA configure register
    /// offset: 0x04
    CONF: mmio.Mmio(packed struct(u32) {
        /// The work mode bits of ECDSA Accelerator. 0: Signature Verify Mode. 1: Signature Generate Mode. 2: Export Public Key Mode. 3: invalid.
        WORK_MODE: u2,
        /// The ecc curve select bit of ECDSA Accelerator. 0: P-192. 1: P-256.
        ECC_CURVE: u1,
        /// The source of k select bit. 0: k is automatically generated by hardware. 1: k is written by software.
        SOFTWARE_SET_K: u1,
        /// The source of z select bit. 0: z is generated from SHA result. 1: z is written by software.
        SOFTWARE_SET_Z: u1,
        /// The source of hardware generated k. 0: k is generated by TRNG. 1: k is generated by deterministic derivation algorithm.
        DETERMINISTIC_K: u1,
        /// The (loop number - 1) value in the deterministic derivation algorithm to derive k.
        DETERMINISTIC_LOOP: u16,
        padding: u10 = 0,
    }),
    /// ECDSA clock gate register
    /// offset: 0x08
    CLK: mmio.Mmio(packed struct(u32) {
        /// Write 1 to force on register clock gate.
        GATE_FORCE_ON: u1,
        padding: u31 = 0,
    }),
    /// ECDSA interrupt raw register, valid in level.
    /// offset: 0x0c
    INT_RAW: mmio.Mmio(packed struct(u32) {
        /// The raw interrupt status bit for the ecdsa_calc_done_int interrupt
        CALC_DONE_INT_RAW: u1,
        /// The raw interrupt status bit for the ecdsa_sha_release_int interrupt
        SHA_RELEASE_INT_RAW: u1,
        padding: u30 = 0,
    }),
    /// ECDSA interrupt status register.
    /// offset: 0x10
    INT_ST: mmio.Mmio(packed struct(u32) {
        /// The masked interrupt status bit for the ecdsa_calc_done_int interrupt
        CALC_DONE_INT_ST: u1,
        /// The masked interrupt status bit for the ecdsa_sha_release_int interrupt
        SHA_RELEASE_INT_ST: u1,
        padding: u30 = 0,
    }),
    /// ECDSA interrupt enable register.
    /// offset: 0x14
    INT_ENA: mmio.Mmio(packed struct(u32) {
        /// The interrupt enable bit for the ecdsa_calc_done_int interrupt
        CALC_DONE_INT_ENA: u1,
        /// The interrupt enable bit for the ecdsa_sha_release_int interrupt
        SHA_RELEASE_INT_ENA: u1,
        padding: u30 = 0,
    }),
    /// ECDSA interrupt clear register.
    /// offset: 0x18
    INT_CLR: mmio.Mmio(packed struct(u32) {
        /// Set this bit to clear the ecdsa_calc_done_int interrupt
        CALC_DONE_INT_CLR: u1,
        /// Set this bit to clear the ecdsa_sha_release_int interrupt
        SHA_RELEASE_INT_CLR: u1,
        padding: u30 = 0,
    }),
    /// ECDSA start register
    /// offset: 0x1c
    START: mmio.Mmio(packed struct(u32) {
        /// Write 1 to start caculation of ECDSA Accelerator. This bit will be self-cleared after configuration.
        START: u1,
        /// Write 1 to input load done signal of ECDSA Accelerator. This bit will be self-cleared after configuration.
        LOAD_DONE: u1,
        /// Write 1 to input get done signal of ECDSA Accelerator. This bit will be self-cleared after configuration.
        GET_DONE: u1,
        padding: u29 = 0,
    }),
    /// ECDSA status register
    /// offset: 0x20
    STATE: mmio.Mmio(packed struct(u32) {
        /// The status bits of ECDSA Accelerator. ECDSA is at 0: IDLE, 1: LOAD, 2: GET, 3: BUSY state.
        BUSY: u2,
        padding: u30 = 0,
    }),
    /// ECDSA result register
    /// offset: 0x24
    RESULT: mmio.Mmio(packed struct(u32) {
        /// The operation result bit of ECDSA Accelerator, only valid when ECDSA calculation is done.
        OPERATION_RESULT: u1,
        /// The k value warning bit of ECDSA Accelerator, valid when k value is bigger than the curve order, then actually taken k = k mod n.
        K_VALUE_WARNING: u1,
        padding: u30 = 0,
    }),
    /// offset: 0x28
    reserved40: [212]u8,
    /// Version control register
    /// offset: 0xfc
    DATE: mmio.Mmio(packed struct(u32) {
        /// ECDSA version control register
        DATE: u28,
        padding: u4 = 0,
    }),
    /// offset: 0x100
    reserved256: [256]u8,
    /// ECDSA control SHA register
    /// offset: 0x200
    SHA_MODE: mmio.Mmio(packed struct(u32) {
        /// The work mode bits of SHA Calculator in ECDSA Accelerator. 1: SHA-224. 2: SHA-256. Others: invalid.
        SHA_MODE: u3,
        padding: u29 = 0,
    }),
    /// offset: 0x204
    reserved516: [12]u8,
    /// ECDSA control SHA register
    /// offset: 0x210
    SHA_START: mmio.Mmio(packed struct(u32) {
        /// Write 1 to start the first caculation of SHA Calculator in ECDSA Accelerator. This bit will be self-cleared after configuration.
        SHA_START: u1,
        padding: u31 = 0,
    }),
    /// ECDSA control SHA register
    /// offset: 0x214
    SHA_CONTINUE: mmio.Mmio(packed struct(u32) {
        /// Write 1 to start the latter caculation of SHA Calculator in ECDSA Accelerator. This bit will be self-cleared after configuration.
        SHA_CONTINUE: u1,
        padding: u31 = 0,
    }),
    /// ECDSA status register
    /// offset: 0x218
    SHA_BUSY: mmio.Mmio(packed struct(u32) {
        /// The busy status bit of SHA Calculator in ECDSA Accelerator. 1:SHA is in calculation. 0: SHA is idle.
        SHA_BUSY: u1,
        padding: u31 = 0,
    }),
    /// offset: 0x21c
    reserved540: [100]u8,
    /// The memory that stores message.
    /// offset: 0x280
    MESSAGE_MEM: [8]u32,
    /// offset: 0x2a0
    reserved672: [1888]u8,
    /// The memory that stores r.
    /// offset: 0xa00
    R_MEM: [8]u32,
    /// The memory that stores s.
    /// offset: 0xa20
    S_MEM: [8]u32,
    /// The memory that stores software written z.
    /// offset: 0xa40
    Z_MEM: [8]u32,
    /// The memory that stores x coordinates of QA or software written k.
    /// offset: 0xa60
    QAX_MEM: [8]u32,
    /// The memory that stores y coordinates of QA.
    /// offset: 0xa80
    QAY_MEM: [8]u32,
};
