const mmio = @import("mmio");
const types = @import("../../types.zig");

/// Parallel IO Controller
pub const PARL_IO = extern struct {
    /// Parallel RX Sampling mode configuration register.
    /// offset: 0x00
    RX_MODE_CFG: mmio.Mmio(packed struct(u32) {
        reserved21: u21 = 0,
        /// Configures rx external enable signal selection from IO PAD.
        RX_EXT_EN_SEL: u4,
        /// Set this bit to enable data sampling by software.
        RX_SW_EN: u1,
        /// Set this bit to invert the external enable signal.
        RX_EXT_EN_INV: u1,
        /// Configures the rxd pulse sampling submode. 4'd0: positive pulse start(data bit included) && positive pulse end(data bit included) 4'd1: positive pulse start(data bit included) && positive pulse end (data bit excluded) 4'd2: positive pulse start(data bit excluded) && positive pulse end (data bit included) 4'd3: positive pulse start(data bit excluded) && positive pulse end (data bit excluded) 4'd4: positive pulse start(data bit included) && length end 4'd5: positive pulse start(data bit excluded) && length end
        RX_PULSE_SUBMODE_SEL: u3,
        /// Configures the rxd sampling mode. 2'b00: external level enable mode 2'b01: external pulse enable mode 2'b10: internal software enable mode
        RX_SMP_MODE_SEL: u2,
    }),
    /// Parallel RX data configuration register.
    /// offset: 0x04
    RX_DATA_CFG: mmio.Mmio(packed struct(u32) {
        reserved9: u9 = 0,
        /// Configures expected byte number of received data.
        RX_BITLEN: u19,
        /// Set this bit to invert bit order of one byte sent from RX_FIFO to DMA.
        RX_DATA_ORDER_INV: u1,
        /// Configures the rxd bus width. 3'd0: bus width is 1. 3'd1: bus width is 2. 3'd2: bus width is 4. 3'd3: bus width is 8.
        RX_BUS_WID_SEL: u3,
    }),
    /// Parallel RX general configuration register.
    /// offset: 0x08
    RX_GENRL_CFG: mmio.Mmio(packed struct(u32) {
        reserved12: u12 = 0,
        /// Set this bit to enable the clock gating of output rx clock.
        RX_GATING_EN: u1,
        /// Configures threshold of timeout counter.
        RX_TIMEOUT_THRES: u16,
        /// Set this bit to enable timeout function to generate error eof.
        RX_TIMEOUT_EN: u1,
        /// Configures the DMA eof generated mechanism. 1'b0: eof generated by data bit length. 1'b1: eof generated by external enable signal.
        RX_EOF_GEN_SEL: u1,
        padding: u1 = 0,
    }),
    /// Parallel RX Start configuration register.
    /// offset: 0x0c
    RX_START_CFG: mmio.Mmio(packed struct(u32) {
        reserved31: u31 = 0,
        /// Set this bit to start rx data sampling.
        RX_START: u1,
    }),
    /// Parallel TX data configuration register.
    /// offset: 0x10
    TX_DATA_CFG: mmio.Mmio(packed struct(u32) {
        reserved9: u9 = 0,
        /// Configures expected byte number of sent data.
        TX_BITLEN: u19,
        /// Set this bit to invert bit order of one byte sent from TX_FIFO to IO data.
        TX_DATA_ORDER_INV: u1,
        /// Configures the txd bus width. 3'd0: bus width is 1. 3'd1: bus width is 2. 3'd2: bus width is 4. 3'd3: bus width is 8.
        TX_BUS_WID_SEL: u3,
    }),
    /// Parallel TX Start configuration register.
    /// offset: 0x14
    TX_START_CFG: mmio.Mmio(packed struct(u32) {
        reserved31: u31 = 0,
        /// Set this bit to start tx data transmit.
        TX_START: u1,
    }),
    /// Parallel TX general configuration register.
    /// offset: 0x18
    TX_GENRL_CFG: mmio.Mmio(packed struct(u32) {
        reserved13: u13 = 0,
        /// Configures the tx eof generated mechanism. 1'b0: eof generated by data bit length. 1'b1: eof generated by DMA eof.
        TX_EOF_GEN_SEL: u1,
        /// Configures bus value of transmitter in IDLE state.
        TX_IDLE_VALUE: u16,
        /// Set this bit to enable the clock gating of output tx clock.
        TX_GATING_EN: u1,
        /// Set this bit to enable the output of tx data valid signal.
        TX_VALID_OUTPUT_EN: u1,
    }),
    /// Parallel IO FIFO configuration register.
    /// offset: 0x1c
    FIFO_CFG: mmio.Mmio(packed struct(u32) {
        reserved30: u30 = 0,
        /// Set this bit to reset async fifo in tx module.
        TX_FIFO_SRST: u1,
        /// Set this bit to reset async fifo in rx module.
        RX_FIFO_SRST: u1,
    }),
    /// Parallel IO FIFO configuration register.
    /// offset: 0x20
    REG_UPDATE: mmio.Mmio(packed struct(u32) {
        reserved31: u31 = 0,
        /// Set this bit to update rx register configuration.
        RX_REG_UPDATE: u1,
    }),
    /// Parallel IO module status register0.
    /// offset: 0x24
    ST: mmio.Mmio(packed struct(u32) {
        reserved31: u31 = 0,
        /// Represents the status that tx is ready to transmit.
        TX_READY: u1,
    }),
    /// Parallel IO interrupt enable singal configuration register.
    /// offset: 0x28
    INT_ENA: mmio.Mmio(packed struct(u32) {
        /// Set this bit to enable TX_FIFO_REMPTY_INT.
        TX_FIFO_REMPTY_INT_ENA: u1,
        /// Set this bit to enable RX_FIFO_WOVF_INT.
        RX_FIFO_WOVF_INT_ENA: u1,
        /// Set this bit to enable TX_EOF_INT.
        TX_EOF_INT_ENA: u1,
        padding: u29 = 0,
    }),
    /// Parallel IO interrupt raw singal status register.
    /// offset: 0x2c
    INT_RAW: mmio.Mmio(packed struct(u32) {
        /// The raw interrupt status of TX_FIFO_REMPTY_INT.
        TX_FIFO_REMPTY_INT_RAW: u1,
        /// The raw interrupt status of RX_FIFO_WOVF_INT.
        RX_FIFO_WOVF_INT_RAW: u1,
        /// The raw interrupt status of TX_EOF_INT.
        TX_EOF_INT_RAW: u1,
        padding: u29 = 0,
    }),
    /// Parallel IO interrupt singal status register.
    /// offset: 0x30
    INT_ST: mmio.Mmio(packed struct(u32) {
        /// The masked interrupt status of TX_FIFO_REMPTY_INT.
        TX_FIFO_REMPTY_INT_ST: u1,
        /// The masked interrupt status of RX_FIFO_WOVF_INT.
        RX_FIFO_WOVF_INT_ST: u1,
        /// The masked interrupt status of TX_EOF_INT.
        TX_EOF_INT_ST: u1,
        padding: u29 = 0,
    }),
    /// Parallel IO interrupt clear singal configuration register.
    /// offset: 0x34
    INT_CLR: mmio.Mmio(packed struct(u32) {
        /// Set this bit to clear TX_FIFO_REMPTY_INT.
        TX_FIFO_REMPTY_INT_CLR: u1,
        /// Set this bit to clear RX_FIFO_WOVF_INT.
        RX_FIFO_WOVF_INT_CLR: u1,
        /// Set this bit to clear TX_EOF_INT.
        TX_EOF_INT_CLR: u1,
        padding: u29 = 0,
    }),
    /// Parallel IO RX status register0
    /// offset: 0x38
    RX_ST0: mmio.Mmio(packed struct(u32) {
        reserved8: u8 = 0,
        /// Indicates the cycle number of reading Rx FIFO.
        RX_CNT: u5,
        /// Indicates the current written bit number into Rx FIFO.
        RX_FIFO_WR_BIT_CNT: u19,
    }),
    /// Parallel IO RX status register1
    /// offset: 0x3c
    RX_ST1: mmio.Mmio(packed struct(u32) {
        reserved13: u13 = 0,
        /// Indicates the current read bit number from Rx FIFO.
        RX_FIFO_RD_BIT_CNT: u19,
    }),
    /// Parallel IO TX status register0
    /// offset: 0x40
    TX_ST0: mmio.Mmio(packed struct(u32) {
        reserved6: u6 = 0,
        /// Indicates the cycle number of reading Tx FIFO.
        TX_CNT: u7,
        /// Indicates the current read bit number from Tx FIFO.
        TX_FIFO_RD_BIT_CNT: u19,
    }),
    /// Parallel IO RX clk configuration register
    /// offset: 0x44
    RX_CLK_CFG: mmio.Mmio(packed struct(u32) {
        reserved30: u30 = 0,
        /// Set this bit to invert the input Rx core clock.
        RX_CLK_I_INV: u1,
        /// Set this bit to invert the output Rx core clock.
        RX_CLK_O_INV: u1,
    }),
    /// Parallel IO TX clk configuration register
    /// offset: 0x48
    TX_CLK_CFG: mmio.Mmio(packed struct(u32) {
        reserved30: u30 = 0,
        /// Set this bit to invert the input Tx core clock.
        TX_CLK_I_INV: u1,
        /// Set this bit to invert the output Tx core clock.
        TX_CLK_O_INV: u1,
    }),
    /// offset: 0x4c
    reserved76: [212]u8,
    /// Parallel IO clk configuration register
    /// offset: 0x120
    CLK: mmio.Mmio(packed struct(u32) {
        reserved31: u31 = 0,
        /// Force clock on for this register file
        EN: u1,
    }),
    /// offset: 0x124
    reserved292: [728]u8,
    /// Version register.
    /// offset: 0x3fc
    VERSION: mmio.Mmio(packed struct(u32) {
        /// Version of this register file
        DATE: u28,
        padding: u4 = 0,
    }),
};
